eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
microservice:
  payment-serviec:
    endpoints:
       fetchPaymentByOrderId:
          uri: "http://PAYMENT-SERVICE/payments/"
  user-service:
     endpoints:
        fetchUserByUserId:
           uri: http://USER-SERVICE/users/

